### ISSUE TITLE
Remove type attributes for CSS and JS tags

### ISSUE THREAD

**Issue by danrichman** [lasso-js/lasso#100]
In HTML5 it’s recommended to omit the type attributes for style sheets (unless not using CSS) and scripts (unless not using JavaScript). Specifying type attributes in these contexts is not necessary as HTML5 implies text/css and text/javascript as defaults. This can be safely done even for older browsers.

See:
http://www.whatwg.org/specs/web-apps/current-work/multipage/semantics.html#attr-style-type
http://www.whatwg.org/specs/web-apps/current-work/multipage/scripting-1.html#attr-script-type
https://google.github.io/styleguide/htmlcssguide.xml?showone=type_Attributes#type_Attributes

**Comment by patrick-steele-idem** [comment]
New version published: `lasso@1.14.0`

Thanks again, @danrichman, for the fix!
