### ISSUE TITLE
test component with lasso tags

### ISSUE THREAD

**Issue by yomed** [lasso-js/lasso#123]
I'd like to be able to test a component which has some lasso tags, but does not have `<lasso-page>`. For example, a `head` component template might look like:

``` html
<meta name="viewport" content="width=device-width" />
<meta name="description" content=data.description />
<meta name="robots" content="All,index,follow" />
<title>${data.title}</title>
<lasso-head />
```

If I try to test the output of this component, like:

``` js
it('renders the template', function (done) {
    out = function (err, html) {
        expect(html).to.equal('...');
        done();
    };
    index({}, out);
});
```

I will get an error on the `<lasso-head>` tag because there's no `<lasso-page>`:

```
Error: Lasso page result not found for slot "head". The <lasso-page> tag should be used to lasso the page.
```

Is there a way to test this without creating a big mock lasso project? Or maybe stub the lasso tag without modifying the original template?

**Comment by yomed** [comment]
I've run into this again recently. Is there a workaround to exclude these lasso tags in testing?

**Comment by mlrawlings** [comment]
If you use
```js
require('marko/compiler').taglibFinder.excludePackage('lasso');
```

You should get `<lasso-head></lasso-head>` in your output instead of a compile error.

**Comment by yomed** [comment]
Thanks @mlrawlings, that should work for v3. For v2 I assume I would need to hack it?
