### ISSUE TITLE
Inline CSS / JS for whole application through config

### ISSUE THREAD

**Issue by RajaRamu** [lasso-js/lasso#129]
Currently, inline resources is possible only in the component level like `{ "path": "b-c2c-banner.less", "inline": true, "slot": "amp-slot” }`. Requesting to have application level flag to control this. this would be helpful for site speed testing. Once master application level inline:true set, it should override all the components below.

As you all know, inlining the CSS speeds up the start rendering(proved in desktop). we want to test this feature on mobile

**Comment by patrick-steele-idem** [comment]
Thanks for opening this issue. We'll definitely be taking a closer look to see how we can implement this, but at this point I can't give you an exact timeline. Please let me know how important this feature is to you and it will help us prioritize.

Thanks!

**Comment by RajaRamu** [comment]
we are targeting next release by end of may. please let me know if you could make it by then

**Comment by patrick-steele-idem** [comment]
Ok, good to know. I'll see if we can squeeze this into our next sprint.

**Comment by patrick-steele-idem** [comment]
This feature has been implemented as part of the following plugin: https://github.com/lasso-js/lasso-inline-slots
