### ISSUE TITLE
inline minification config options don't accept `false`

### ISSUE THREAD

**Issue by yomed** [lasso-js/lasso#130]
I'm trying to use `minifyInlineOnly: true` by default, and then override it to `minifyInlineOnly: false` in different environments. 

It looks like the code only accepts the presence of the config and not the actual value:
```
        minifyInlineJSOnly: function(value) {
            config.addPlugin(minifyJSPlugin, config._minifyJSPluginConfig);
            config._minifyJSPluginConfig.inlineOnly = true;
        },
```

Would be a quick PR to fix it (I guess to both v1 and v2?), but wanted to check with you if there was a reason that we avoid doing an `if (value)` check here, like in the other config options.

**Comment by patrick-steele-idem** [comment]
Nope, there was not a reason... that was an oversight on my part. If you don't mind sending a PR that would be helpful. Sorry about that and thanks in advance!
