### ISSUE TITLE
latest on npm is 1.20.0

### ISSUE THREAD

**Issue by juliangruber** [lasso-js/lasso#144]
is lasso@2 unstable? otherwise npm currently thinks 1.20.0 is the most recent version, which I guess comes from publishing it after a release of version 2. in that case, you need to publish it with a tag, like `npm publish --tag v1`

**Comment by patrick-steele-idem** [comment]
Sorry for the extremely delayed response, but thank you for reporting the problem. I was npm was smart enough to not tag a package as latest if there is a newer version that is already marked as latest but oh well :/ Thanks, again.
