### ISSUE TITLE
if-flag is ignored in async section of browser.json

### ISSUE THREAD

**Issue by mikewoo200** [lasso-js/lasso#149]
if-flag is ignored in the async section. The file is downloaded to browser regardless of whether the lasso flag is passed in or not. In the following example, `./myFile.js` is always loaded, with or without `someFlag`

```
...
"async": {
  "some-module/lazy": [
    {
      "if-flag": "someFlag",
      "dependencies": [
        "./myFile.js"
      ]
    },
    ...
```

**Comment by patrick-steele-idem** [comment]
Thanks for reporting the problem.

New versions published with fix:

- `lasso@1.20.1`
- `lasso@2.5.4`

Please let me know if you see any other issues.

Thanks,
Patrick
