### ISSUE TITLE
Broken Build on all Node Versions

### ISSUE THREAD

**Issue by StarpTech** [lasso-js/lasso#199]
Anybody working on this?

**Comment by patrick-steele-idem** [comment]
We have a one fragile test due to a fingerprint. Taking a look now. Thanks for the reminder!

**Comment by patrick-steele-idem** [comment]
Broken build has been fixed. Thanks again,.

**Comment by StarpTech** [comment]
@patrick-steele-idem thanks for fix.

**Comment by StarpTech** [comment]
BTW: Gitter chat badge is broken
