### ISSUE TITLE
Transpile to support Node 6

### ISSUE THREAD

**Issue by austinkelleher** [lasso-js/lasso#236]
We also need to do Node version detection to point to either a `dist-compat` directory or `src`. If `process.version >= 'v8.0.0'`, we should use `src`.

**Comment by zephraph** [comment]
Ah, yes, that's why there's an `async` function in lasso that marko-starter is choking on 😄 . I think at least supporting whatever the current LTS is would be good.

**Comment by austinkelleher** [comment]
@zephraph That should only be for `marko-starter@2.0.0`. Also, this change should be by tomorrow.
