### ISSUE TITLE
How to precompile all assets

### ISSUE THREAD

**Issue by nguyenpc** [lasso-js/lasso#239]
I'm using lasso as a bundle tool for my ExpressJS project which using MarkoJS as a view engine. Everything work fine. When I access a page, lasso bundle assets (JS, css, images) as configured to my static folder.
But it seems only bundle assets at run time. I just want to ask if there is some methods to pre-compile (pre-bundle) assets? So server won't need to do that again?

**Comment by FiW** [comment]
Hello. You can try this https://github.com/schetnikovich/lasso-marko-extras

**Comment by nguyenpc** [comment]
@FiW Many thanks for the link. my problem seems to be resolved
