### ISSUE TITLE
Missing plugin: optimizer-autoprefixer

### ISSUE THREAD

**Issue by patrick-steele-idem** [lasso-js/lasso#24]
Someone should create a plugin to integrate the [autoprefixer](https://www.npmjs.org/package/autoprefixer-core) module.

**Comment by philidem** [comment]
:+1:

**Comment by yomed** [comment]
Looks like you can close per https://github.com/lasso-js/lasso-autoprefixer

**Comment by patrick-steele-idem** [comment]
Yes, thanks.
