### ISSUE TITLE
minifyInlineOnly breaks with lasso 3.2.0

### ISSUE THREAD

**Issue by scttdavs** [lasso-js/lasso#272]
Lasso recently updated uglify-js to v3. With that new change, this now breaks:
https://github.com/lasso-js/lasso/blob/master/src/plugins/lasso-minify-js/index.js#L5

as the plugin config of:
```js
{ inlineOnly: true }
```

is passed to uglify-js, which in turn fails due to an unrecognized option. That option is meant for lasso, not uglify-js, so it should not be passed to it. This appears to be a new behavior for uglify-js with the upgrade from v2 to v3.

**Comment by DylanPiercey** [comment]
Fixed in v3.2.2 😄
