### ISSUE TITLE
Create Marko tag to read image info into variable

### ISSUE THREAD

**Issue by philidem** [lasso-js/lasso#36]
## OPTION 1:
Create new `<optimizer-image-info>` tag to read image metadata:
```xml
<optimizer-image-info src="someFilePath" var="imageInfo" />
<img src="imageInfo.url" width="imageInfo.width" height="imageInfo.height" /> 
```

## OPTION 2:
Extend existing `<optimizer-resource>` tag to conditionally read image information:
```xml
<optimizer-resource path="someFilePath" image-type="png" var="imageInfo"/>
<img src="imageInfo.url" width="imageInfo.width" height="imageInfo.height" /> 
```
NOTE: Presence of `image-type` attribute would trigger reading of image metadata (width and height at a minimum)

---

This tag should leverage:
https://github.com/raptorjs/optimizer-image

**Comment by philidem** [comment]
I am in favor of **OPTION 2**

**Comment by patrick-steele-idem** [comment]
I'm in favor or __OPTION 1__, but with the following slightly different syntax:

```html
<optimizer-image-info path="./some-image.png" var="imageInfo" />
<img src="${imageInfo.url}" width="${imageInfo.width}" height="${imageInfo.height}" /> 
```

**Comment by philidem** [comment]
Yes, `path` was a better choice for attribute name. Maybe **OPTION 1** is cleaner so that `<optimizer-resource>` doesn't become a confusing mess.

**Comment by patrick-steele-idem** [comment]
Also, the logic for reading images to get width and height resides in the [optimizer-image](https://github.com/raptorjs/optimizer-image) module so it is better for the tag name to be prefixed with "optimizer-image"

**Comment by philidem** [comment]
Was this ever implemented?

**Comment by patrick-steele-idem** [comment]
This was implemented as part of the [lasso-image](https://github.com/lasso-js/lasso-image) plugin. Closing this issue.
