### ISSUE TITLE
Error: Reading dependency timed out after 

### ISSUE THREAD

**Issue by onemrkarthik** [lasso-js/lasso#54]
Quite often, my node app crashes due to the following error from the optimizer:

uncaughtException Async fragment failed (optimizer-slot:head). Exception: Error: Error while writing bundle "index (body, js)" Error: Error: Reading dependency timed out after 5000ms: [js: path="/app/src/static/js/jquery.min.js"]

Optimizer version: 1.8.2

I also use the minification modules, "optimizer-minify-js": "^1.1.2" and  "optimizer-minify-css": "^1.1.2" 

Please advice. 

Karthik

**Comment by patrick-steele-idem** [comment]
Sorry for the delayed response, but better late than never. Just wanted to follow up and see if you are still seeing this error with the latest code base. Also, if you are not using the default file writer and, instead, using a plugin that uploads resources to a resource server then the timeout could be happening during the upload. Please let us know if you are still seeing problems.

**Comment by zanzamar** [comment]
Hey.  I wanted to post a quick note here regarding this.

We ran into this issue and had some issues trying to track it down.

Basically it came down to the fact that one of our AWS instances was under performing and would not process the individual file with in the timeout window.

It is not really "documented", but if you look at `node_modules/optimizer/lib/config-loader.js` you will see that `bundleReadTimeout` is a parameter which can be set in the optimizer config object.  We increase our timeout and have had no issues sense...  

Now to increase the base size of our aws instances...

**Comment by patrick-steele-idem** [comment]
Thanks for sharing @zanzamar. My take away is that the timeout error message should include details on how to increase the timeout. I'll open a separate Github issue. Thanks for the update!

**Comment by jayaprakash1210** [comment]
Thanks for sharing. Can you provide the steps to increase the timeout.

**Comment by laggingreflex** [comment]
lasso.configure({
      bundleReadTimeout: 10000,
    })

**Comment by patrick-steele-idem** [comment]
Thanks for sharing @laggingreflex. I'll make a change to show this info in the error message so that a developer will know how to fix the problem when encountered without having to read through the docs.
