### ISSUE TITLE
Browser overrides should support relative paths that do not start with "./"

### ISSUE THREAD

**Issue by philidem** [lasso-js/lasso#67]
It looks like browserify is fairly lenient about this:
```json
{
    "browser": "index-browser.js"
}
```

Lasso, however, assumes that if the path does not start with `.` then it is a module name. I think we should try the module name and then if that fails, try resolving it as a relative path. The performance will be better if the author uses "./index-browser.js" in this use case but I think Lasso needs to tolerate this (since module authors are not always prefixing their relative paths with `.`).

**Comment by patrick-steele-idem** [comment]
I agree. I think this would be a good change.

**Comment by philidem** [comment]
This was fixed via change to https://github.com/raptorjs/raptor-modules
