### ISSUE TITLE
minify inline javascript

### ISSUE THREAD

**Issue by yomed** [lasso-js/lasso#73]
Is there a way to minify inline resources? I set up a custom slot, and then include my js file through browser.json:

```
        {
            "path": "awesome.js",
            "slot": "inline-js",
            "inline": true
        }
```

But the resulting output has the javascript inlined without minification.

**Comment by patrick-steele-idem** [comment]
Did you enable minification via the config? `{ minify: true, ... }`

Inline JS should still be minified.

**Comment by yomed** [comment]
I'll see myself out...
