### ISSUE TITLE
Need support to make lasso a true singleton (using a global variable)

### ISSUE THREAD

**Issue by saraxu** [lasso-js/lasso#82]
I have a page in a installed module which get less dependency issue when referenced from the main application.

**Comment by patrick-steele-idem** [comment]
For more details:

We found an issue when using the Lasso tags from installed modules. Most apps have all their pages in the main application where lasso is configured. We are seeing problems if an installed module has its own instance of `lasso` (i.e. `node_modules/some-installed-module/node_modules/lasso`) that is different from the lasso configured at the main application level (i.e. `node_modules/lasso`). The `lasso` in the main application is configured correctly, while the lasso used by the installed module is using a separate `lasso` instance with the default configuration..

**Comment by patrick-steele-idem** [comment]
New version published: `lasso@1.11.12`

Make sure the new version lasso is used in both the application and in the installed project. I tested the fix locally and it solved the problem. Let us know if you still see issues.
